apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cargo-build
  labels:
    app.kubernets.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "build-tool, rust"
    tekton.dev/displayName: "Cargo Build"
spec:
  description: >-
    This task builds rust source code via the official rust image on the docker hub. 
  params:
    - name: compile-flags
      type: array
      description: Compilation flags passed to cargo build. Results in 'cargo build $param1 $param2 $param3...'
      default: []
    - name: rust-version
      type: string
      description: The rust version to use. Gets passed as the image tag. Results in 'docker.io/rust:$version'
      default: latest
  steps:
    - name: build
      image: docker.io/rust:$(params.rust-version)
      command: [cargo]
      args: ["build", "$(params.compile-flags[*])"]

