apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: cargo
  labels:
    app.kubernets.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "build-tool, rust"
    tekton.dev/displayName: "Cargo"
spec:
  description: >-
    This task executes cargo commands via the official rust image on the docker hub. 
  workspaces:
    - name: source
      description: The workspace that contains your cargo.toml and rust code. This will be the working directory.
  params:
    - name: COMMAND
      type: string
      default: build
    - name: COMPILE_FLAGS
      type: array
      description: Compilation flags passed to cargo build. Results in 'cargo build $param1 $param2 $param3...'
      default: []
    - name: RUST_VERSION
      type: string
      description: The rust version to use. Gets passed as the image tag. Results in 'docker.io/rust:$version'
      default: latest
  steps:
    - name: cargo-command
      image: docker.io/rust:$(params.RUST_VERSION)
      workingDir: $(workspaces.source.path)
      command: [cargo]
      args: ["$(params.COMMAND)", "$(params.COMPILE_FLAGS[*])"]

