apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cargo-build
spec:
  params:
    - name: compile-flags
      type: array
      description: Compilation flags passed to cargo. Results in 'cargo build {params...}'
  steps:
    - name: build
      image: docker.io/rust:1.52.1
      command: [cargo]
      args: ["build", "${params.compile-flags[*]}"]

