apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rust
  labels:
    app.kubernetes.io/version: '0.2'
  annotations:
    tekton.dev/displayName: "Rust"
    tekton.dev/pipelines.minVersion: '0.12.1'
    tekton.dev/tags: "build, push, deploy, rust"
spec:
  description: >-
    This pipeline is a complete solution to build and containerize your rust applications.
  workspaces:
    - name: source
      description: The workspace that contains your cargo.toml and rust code. This will be the working directory. If this directory does not contain your source, set the context path aswell.
    - name: ssh-creds
      description: The secret that contains your ssh credentials.
      optional: true
  params:
    - name: GIT_URI
      type: string
      description: The git url that contains your source code.
    - name: CONTEXT_PATH
      type: string
      description: The context path for your sources
      default: .
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
        - name: ssh-credentials
          workspace: ssh-creds
          optional: true
      params:
        - name: url
          value: '$(params.GIT_URI)'
